yourName = input("What is your name?")
yourFood = input("What is your favorite food?")
yourMusic = input("What is your favorite music?")
yourLocation = input("Where do you live?")
print("Your name is")
print(yourName)
print("Your favorite food is")
print(yourFood)
print("Your favorite music is")
print(yourMusic)
print("You live in")
print(yourLocation)
print("You are awesome")
